DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  firstName VARCHAR(250) DEFAULT NULL,
  lastName VARCHAR(250) DEFAULT NULL,
  dept VARCHAR(250) DEFAULT NULL
);